#!/bin/bash
clear
echo -e "\E[44;1;37m     INSTALACAO SSH    \E[0m"
echo -e "\nINSTALANDO AGUARDE...."
apt update -y > /dev/null 2>&1 && apt install unzip jq sshpass curl at apache2 php libapache2-mod-php php-curl -y > /dev/null 2>&1
echo -e "\nCONFIGURANDO AGUARDE...."
cd /var/www/html
wget https://github.com/NT-GIT-HUB/SSH/raw/main/SSH.zip
unzip SSH.zip
clear
echo -e "INSTALADO COM SUCESSO!"
cd $HOME